server:
  port: 8099
  servlet:
    session:
      timeout: 30m
  tomcat:
    max-http-form-post-size: -1
spring:
  datasource:
    dynamic:
      p6spy: false
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:postgresql://localhost:5433/ninetwo-1
          username: postgres
          password: your-db-password
          driver-class-name: org.postgresql.Driver
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            minimum-idle: 3
            maximum-pool-size: 10
            auto-commit: true
            idle-timeout: 30000
            pool-name: MyHikariCP
            max-lifetime: 120000
            connection-timeout: 30000
            connection-test-query: SELECT 1
        slave:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5433/ninetwo-2
          username: postgres
          password: your-db-password
          hikari:
            minimum-idle: 3
            maximum-pool-size: 10
            auto-commit: true
            idle-timeout: 30000
            pool-name: MyHikariCP
            max-lifetime: 120000
            connection-timeout: 30000
            connection-test-query: SELECT 1
  jpa:
    database: DEFAULT
    show-sql: false
    generate-ddl: true
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: com.ninetwo.boot.config.Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
  mvc:
    servlet:
      load-on-startup: 1
  mail:
    host: smtp.example.com
    port: 465
    username: your-email@example.com
    password: 'your-email-auth-code'
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
  mapper-locations: classpath:mapper/*Mapping.xml
  type-aliases-package: com.ninetwo.*.*
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
token:
  expire:
    seconds: 86400
log:
  level:
    maxsize: 30MB
logging:
  level:
    com.ninetwo.boot.interceptor: INFO

file-storage:
  path: ./files/
